import type { Plan, Content } from "@/types"

export const plans: Plan[] = [
  {
    id: "basic",
    name: "Básico",
    price: "$5",
    originalPrice: "$8",
    features: ["1 pantalla simultánea", "Calidad SD", "Catálogo completo", "Sin anuncios", "Soporte 24/7"],
    screens: 1,
    quality: "SD",
    popular: false,
    discount: 37,
  },
  {
    id: "standard",
    name: "Estándar",
    price: "$10",
    originalPrice: "$15",
    features: [
      "2 pantallas simultáneas",
      "Calidad HD",
      "Catálogo completo",
      "Sin anuncios",
      "Descargas offline",
      "Soporte prioritario",
    ],
    screens: 2,
    quality: "HD",
    popular: true,
    discount: 33,
  },
  {
    id: "premium",
    name: "Premium",
    price: "$15",
    originalPrice: "$25",
    features: [
      "4 pantallas simultáneas",
      "Calidad 4K Ultra HD",
      "Catálogo completo",
      "Sin anuncios",
      "Descargas offline",
      "Audio espacial",
      "Acceso anticipado",
      "Soporte VIP",
    ],
    screens: 4,
    quality: "4K",
    popular: false,
    discount: 40,
  },
]

export const featuredContent: Content[] = [
  {
    id: "1",
    title: "Acción Extrema",
    type: "Película",
    rating: 4.8,
    year: "2024",
    genre: "Acción",
    image: "/images/accion-extrema.png",
    description:
      "Una película llena de adrenalina con efectos especiales impresionantes y secuencias de acción épicas.",
    duration: "2h 15min",
    featured: true,
    trending: true,
  },
  {
    id: "2",
    title: "Misterios Urbanos",
    type: "Serie",
    rating: 4.6,
    year: "2024",
    genre: "Thriller",
    image: "/images/misterios-urbanos.png",
    description: "Una serie de suspenso que te mantendrá al borde del asiento con cada episodio.",
    seasons: 3,
    featured: true,
    trending: false,
  },
  {
    id: "3",
    title: "Naturaleza Salvaje",
    type: "Documental",
    rating: 4.9,
    year: "2024",
    genre: "Naturaleza",
    image: "/images/naturaleza-salvaje.png",
    description: "Explora los rincones más remotos de nuestro planeta con imágenes espectaculares.",
    duration: "1h 45min",
    featured: true,
    trending: true,
  },
  {
    id: "4",
    title: "Comedia Central",
    type: "Serie",
    rating: 4.4,
    year: "2024",
    genre: "Comedia",
    image: "/images/comedia-central.png",
    description: "Risas garantizadas con esta divertida serie familiar llena de momentos memorables.",
    seasons: 2,
    featured: false,
    trending: true,
  },
  {
    id: "5",
    title: "Ciencia Ficción",
    type: "Película",
    rating: 4.7,
    year: "2024",
    genre: "Sci-Fi",
    image: "/images/ciencia-ficcion.png",
    description: "Un viaje épico a través del espacio y el tiempo con tecnología futurista.",
    duration: "2h 30min",
    featured: true,
    trending: false,
  },
  {
    id: "6",
    title: "Drama Histórico",
    type: "Serie",
    rating: 4.5,
    year: "2024",
    genre: "Drama",
    image: "/images/drama-historico.png",
    description: "Una emotiva historia basada en hechos reales que marcaron la historia.",
    seasons: 1,
    featured: false,
    trending: false,
  },
  {
    id: "7",
    title: "Terror Nocturno",
    type: "Película",
    rating: 4.3,
    year: "2023",
    genre: "Terror",
    image: "/images/terror-nocturno.png",
    description: "Una película de terror psicológico que te quitará el sueño por semanas.",
    duration: "1h 55min",
    featured: false,
    trending: true,
  },
  {
    id: "8",
    title: "Romance Eterno",
    type: "Película",
    rating: 4.2,
    year: "2023",
    genre: "Romance",
    image: "/images/romance-eterno.png",
    description: "Una historia de amor que trasciende el tiempo y las circunstancias.",
    duration: "2h 05min",
    featured: false,
    trending: false,
  },
  {
    id: "9",
    title: "Aventura Espacial",
    type: "Película",
    rating: 4.6,
    year: "2024",
    genre: "Aventura",
    image: "/images/aventura-espacial.png",
    description: "Una épica aventura intergaláctica con criaturas alienígenas y mundos inexplorados.",
    duration: "2h 20min",
    featured: true,
    trending: true,
  },
  {
    id: "10",
    title: "Detectives Modernos",
    type: "Serie",
    rating: 4.7,
    year: "2024",
    genre: "Thriller",
    image: "/images/detectives-modernos.png",
    description: "Sigue a un equipo de detectives resolviendo los casos más complejos de la ciudad.",
    seasons: 2,
    featured: true,
    trending: true,
  },
  {
    id: "11",
    title: "Fantasía Épica",
    type: "Serie",
    rating: 4.8,
    year: "2024",
    genre: "Fantasía",
    image: "/images/fantasia-epica.png",
    description: "Un mundo mágico lleno de dragones, hechiceros y batallas épicas por el poder.",
    seasons: 4,
    featured: true,
    trending: true,
  },
  {
    id: "12",
    title: "Documental Océanos",
    type: "Documental",
    rating: 4.9,
    year: "2024",
    genre: "Naturaleza",
    image: "/images/documental-oceanos.png",
    description: "Sumérgete en las profundidades del océano y descubre sus secretos mejor guardados.",
    duration: "1h 30min",
    featured: false,
    trending: false,
  },
  {
    id: "13",
    title: "Comedia Familiar",
    type: "Película",
    rating: 4.1,
    year: "2023",
    genre: "Comedia",
    image: "/images/comedia-familiar.png",
    description: "Una divertida comedia perfecta para disfrutar en familia con momentos entrañables.",
    duration: "1h 40min",
    featured: false,
    trending: false,
  },
  {
    id: "14",
    title: "Thriller Psicológico",
    type: "Película",
    rating: 4.5,
    year: "2024",
    genre: "Thriller",
    image: "/images/thriller-psicologico.png",
    description: "Un thriller que juega con tu mente y te mantiene adivinando hasta el final.",
    duration: "2h 10min",
    featured: true,
    trending: true,
  },
  {
    id: "15",
    title: "Biografía Inspiradora",
    type: "Película",
    rating: 4.6,
    year: "2024",
    genre: "Drama",
    image: "/images/biografia-inspiradora.png",
    description: "La increíble historia real de una persona que cambió el mundo contra todas las probabilidades.",
    duration: "2h 25min",
    featured: true,
    trending: false,
  },
  {
    id: "16",
    title: "Animación Familiar",
    type: "Película",
    rating: 4.4,
    year: "2024",
    genre: "Animación",
    image: "/images/animacion-familiar.png",
    description: "Una hermosa película animada con lecciones de vida y personajes entrañables.",
    duration: "1h 35min",
    featured: false,
    trending: true,
  },
  {
    id: "17",
    title: "Serie Criminal",
    type: "Serie",
    rating: 4.7,
    year: "2024",
    genre: "Drama",
    image: "/images/serie-criminal.png",
    description: "Sigue la investigación de crímenes complejos con giros inesperados en cada episodio.",
    seasons: 3,
    featured: true,
    trending: true,
  },
  {
    id: "18",
    title: "Documental Histórico",
    type: "Documental",
    rating: 4.8,
    year: "2024",
    genre: "Historia",
    image: "/images/documental-historico.png",
    description: "Un fascinante recorrido por los eventos que cambiaron el curso de la humanidad.",
    duration: "2h 00min",
    featured: false,
    trending: false,
  },
]

export const genres = [
  "Todos",
  "Acción",
  "Comedia",
  "Drama",
  "Thriller",
  "Sci-Fi",
  "Naturaleza",
  "Terror",
  "Romance",
  "Aventura",
  "Fantasía",
  "Animación",
  "Historia",
]

export const contentTypes = ["Todos", "Películas", "Series", "Documentales"]

export const years = ["Todos", "2024", "2023", "2022", "2021", "2020"]
